//
// Generated file, do not edit! Created by nedtool 5.4 from prior_message.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __PRIOR_MESSAGE_M_H
#define __PRIOR_MESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>prior_message.msg:2</tt> by nedtool.
 * <pre>
 * message PriorMessage extends cMessage
 * {
 *     int priority;
 * 
 * }
 * </pre>
 */
class PriorMessage : public ::omnetpp::cMessage
{
  protected:
    int priority;

  private:
    void copy(const PriorMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PriorMessage&);

  public:
    PriorMessage(const char *name=nullptr, short kind=0);
    PriorMessage(const PriorMessage& other);
    virtual ~PriorMessage();
    PriorMessage& operator=(const PriorMessage& other);
    virtual PriorMessage *dup() const override {return new PriorMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPriority() const;
    virtual void setPriority(int priority);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PriorMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PriorMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PRIOR_MESSAGE_M_H

